theme: jekyll-theme-minimal
title: Machine Learning for Trading
description: A comprehensive introduction to how ML can add value to the design and execution of algorithmic trading strategies
logo: assets/ml4t_cover.png